version: '3'
services:
  edge-service:
    build: ./
    ports:
     - "8080:8080"
     depends_on:
       - discovery-service
  discovery-service:
    image: springcloud/eureka
    ports:
      - "8761:8761"
