version: '3'

services:

  edge-service:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service

  discovery-service:
    image: springcloud/eureka
    ports:
      - "8761:8761"
    container_name: eureka-server

#  hystrix-dashboard:
#    image: kbastani/hystrix-dashboard
#    container_name: hystrix-dashboard
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - 6161:6161

#  config-service:
#    build: config-service
#    container_name: config-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - 8888:8888

  mysql-server:
    image: mysql:5.7
    container_name: mysql-server
    volumes:
      - mysql-data:/var/lib/mysql:rw
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'user_service'

  microservice--user-service:
    image: aista/user-service
    depends_on:
      - discovery-service
      - mysql-server
    container_name: microservice--user-service
    ports:
      - '8091:8091'

  mongo:
    image: 'mongo:3.4.1'
    container_name: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"

  trip-management-cmd:
    image: aista/trip-management-cmd
    container_name: trip-management-cmd
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    ports:
      - '8080'
    depends_on:
      - discovery-service
      - rabbitmq
      - mongo

  trip-management-query:
    image: aista/trip-management-query
    container_name: trip-management-query
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    ports:
      - '8080'
    depends_on:
      - rabbitmq
      - mongo
      - discovery-service 

volumes:
  mongo:
  mysql-data: