version: '3'

services:

  edgeservice:
    image: aista/edge-service
    ports:
      - "8080:8080"
    depends_on:
      - discoveryservice

  notificationservice:
    depends_on:
      - discoveryservice
      - rabbitmq
    image: aista/notification-service
    command: notification-service
    ports:
      - "32700:32700"
    environment:
      - RABBIT_HOST=rabbitmq
      - EUREKA_SERVER=discoveryservice

  discoveryservice:
    image: aista/eureka
    ports:
      - "8761:8761"

#  hystrix-dashboard:
#    image: kbastani/hystrix-dashboard
#    container_name: hystrix-dashboard
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - 6161:6161
#
#  config-service:
#    build: config-service
#    container_name: config-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - 8888:8888

  mysqlserver:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql:rw
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'user_service'

  userservice:
    image: aista/user-service
    depends_on:
      - discoveryservice
      - mysqlserver
    ports:
      - '8080'

  mongo:
    image: 'mongo:3.4.1'
    container_name: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'passenger_db'
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      PGDATA: ./postgres-data
    ports:
      - '5432:5432'
    volumes:
      - ./db_volume:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"

  tripmanagementcmd:
    image: aista/trip-management-cmd
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    ports:
      - '8080'
    depends_on:
      - discoveryservice
      - rabbitmq
      - mongo

  tripmanagementquery:
    image: aista/trip-management-query
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    ports:
      - '8080'
    depends_on:
      - rabbitmq
      - mongo
      - discoveryservice

  gmaps-adapter:
    image: aista/gmaps-adapter
    environment:
      - EUREKA_SERVER=discoveryservice
      - RABBIT_HOST=rabbitmq
    ports:
      - '8080'
    depends_on:
      - discoveryservice

  calculation-service:
    image: aista/calculation-service
    environment:
      - EUREKA_SERVER=discoveryservice
      - RABBIT_HOST=rabbitmq
    command: ["go", "run", "main.go"]
    ports:
      - '8080'
    depends_on:
      - discoveryservice

  passenger:
    image: aista/passenger
    ports:
      - '8080'
    depends_on:
      - postgres
      - discoveryservice

  driver-cmd:
    image: aista/driver-cmd
    environment:
      - EUREKA_SERVER=discoveryservice
    ports:
      - '8080'
    depends_on:
      - rabbitmq
      - mongo
      - discoveryservice

  driver-query:
    image: aista/driver-query
    container_name: 'driver-query'
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    ports:
      - "8080"
    depends_on:
      - rabbitmq
      - mongo
      - discoveryservice

volumes:
  mongo:
  mysql-data: