---
spring:
  profiles: development
  application:
    name: edgeservice
zuul:
  prefix: /api
  routes:
    trip-cmd:
      path: /trip/cmd/**
      url: http://${TRIP_CMD_HOST:localhost}:8080/api
    trip-query:
      path: /trip/query/**
      url: http://${TRIP_QUERY_HOST:localhost}:8080/api
    userservice:
      path: /${USER_SERVICE_HOST:localhost}/**
      url: http://${USER_SERVICE_HOST:localhost}:8080/
      sensitiveHeaders: Cookie,Set-Cookie
security:
  oauth2:
    resource:
      userInfoUri: http://${USER_SERVICE_HOST:localhost}:8080/auth/user
  ignored: /catalog/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/
management:
  security:
    enabled: false
  context-path: /actuator
  
---
spring:
  profiles: docker
  application:
    name: edgeservice
zuul:
  prefix: /api
  routes:
    trip-cmd:
      path: /trip/cmd/**
      url: http://tripmanagementcmd:8080/api
    trip-query:
      path: /trip/query/**
      url: http://tripmanagementquery:8080/api
    userservice:
      path: /userservice/**
      url: http://userservice:8080/
      sensitiveHeaders: Cookie,Set-Cookie
security:
  oauth2:
    resource:
      userInfoUri: http://userservice:8080/auth/user
  ignored: /catalog/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discoveryservice:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
ReadTimeout: 60000

---
spring:
  profiles: local
  application:
    name: edgeservice
zuul:
  prefix: /api
  routes:
    trip-cmd:
      path: /trip/cmd/**
      url: http://${DOCKER_MACHINE_IP:localhost}:8080/api
    trip-query:
      path: /trip/query/**
      url: http://${DOCKER_MACHINE_IP:localhost}:8080/api
    userservice:
      path: /userservice/**
      url: http://${DOCKER_MACHINE_IP:localhost}:8080/
      sensitiveHeaders: Cookie,Set-Cookie
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_MACHINE_IP:localhost}:8080/auth/user
  ignored: /catalog/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DOCKER_MACHINE_IP:localhost}:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
ReadTimeout: 60000