spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: edgeservice
zuul:
  prefix: /api
  routes:
    trip-cmd:
      path: /trip/cmd/**
      url: http://tripmanagementcmd:8080/api
    trip-query:
      path: /trip/query/**
      url: http://tripmanagementquery:8080/api
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/uaa/user
  ignored: /catalog/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
management:
  security:
    enabled: false
  context-path: /actuator
---
spring:
  profiles: docker
  application:
    name: edgeservice
zuul:
  prefix: /api
  routes:
    trip-cmd:
      path: /trip/cmd/**
      url: http://tripmanagementcmd:8080/api
    trip-query:
      path: /trip/query/**
      url: http://tripmanagementquery:8080/api
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
  ignored: /catalog/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
ReadTimeout: 60000